### ISSUE TITLE
np0-9 not working on windows

### ISSUE THREAD

**Issue by s0hv** [timeyyy/system_hotkey#3]
The program changes the "np" to "numpad" so it doesn't match in get_callback and it raises MFERROR. You could just  completely remove the "np" keys and keep the "numpad" ones because they work.

Edit: Looks like it doesn't know wich of the numpads to choose
`{('alt', 'numpad3'): <function <lambda> at 0x00000000046C4D08>}`
`MFERROR ['alt', 'np3']`

**Comment by timeyyy** [comment]
**Linux**
The issue is that i have not taken into account modifiers such as numpad/caps lock etc.
I need to read this and make some adjustments https://tronche.com/gui/x/xlib/input/keyboard-encoding.html

**Windows**
I don't have access to my windows box but you are correct( it doesn't know which one to use ), This highlights a bigger issue. 

On windows the key numpad3 or np3 will work, while on linux KP_3 is required. This breaks our cross platformness. I will probably decide on the xwindows keys for the standard. https://github.com/substack/node-keysym/blob/master/data/keysyms.txt
